### PR TITLE
Color from hex update

### PR DESCRIPTION
**Pull request by lucillebenoit**
### Summary

Updates the color from hex initializer to use `scanHexInt64`

### CODE REVIEW

**Comment by lucillebenoit** [comment]
Current dependencies on/for this PR:
* main
  * **PR #87** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87" target="_blank">Graphite</a>  👈
    * **PR #88** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87?utm_source=stack-comment).

**Review by clarksandholtz — APPROVED** [review]
image

**Comment by lucillebenoit** [comment]
@lucillebenoit started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87).

**Comment by lucillebenoit** [comment]
@lucillebenoit merged this pull request with [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87).

**Pull request merged**
