### PR TITLE
Update callout widgets to default to no border

### PR DESCRIPTION
**Pull request by lucillebenoit**
### Summary

Updates the callout widgets to default to no border instead of the rounded rectangle style border.

### CODE REVIEW

**Comment by lucillebenoit** [comment]
Current dependencies on/for this PR:
* main
  * **PR #87** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87" target="_blank">Graphite</a> 
    * **PR #88** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88?utm_source=stack-comment).

**Review by clarksandholtz — APPROVED** [review]

**Comment by lucillebenoit** [comment]
@lucillebenoit started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88).

**Comment by lucillebenoit** [comment]
[Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88) rebased this pull request as part of a merge.

**Comment by lucillebenoit** [comment]
@lucillebenoit merged this pull request with [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88).

**Pull request merged**
