### PR TITLE
Support iPad Multiple Scenes

### PR DESCRIPTION
**Pull request by lucillebenoit**
### Summary

This PR adds support for iPads with multiple scenes in the `UIApplication` extension. With the introduction of multiple scenes in iOS 13, iPads can have multiple windows and view controllers, requiring adjustments to the existing code.

To handle iPads with multiple scenes, the `topViewController()` method in the `UIApplication` extension has been updated. The changes ensure that the topmost view controller is correctly determined, taking into account both the primary scene and additional connected scenes.

### CODE REVIEW

**Comment by lucillebenoit** [comment]
Current dependencies on/for this PR:
* main
  * **PR #90** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/90" target="_blank">Graphite</a> 
    * **PR #91** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/91" target="_blank">Graphite</a>  👈
      * **PR #92** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/92" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/91?utm_source=stack-comment).

**Review by clarksandholtz — APPROVED** [review]
Fascinating!

**Comment by lucillebenoit** [comment]
@lucillebenoit started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/91).

**Comment by lucillebenoit** [comment]
[Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/91) rebased this pull request as part of a merge.

**Comment by lucillebenoit** [comment]
@lucillebenoit merged this pull request with [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/91).

**Pull request merged**
