### PR TITLE
Remove unused fonts

### PR DESCRIPTION
**Pull request by lucillebenoit**
### Summary

Removes all CircularStd fonts that are not directly used by the SDK.

### CODE REVIEW

**Comment by lucillebenoit** [comment]
Current dependencies on/for this PR:
* main
  * **PR #87** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/87" target="_blank">Graphite</a> 
    * **PR #88** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/88" target="_blank">Graphite</a> 
      * **PR #89** <a href="https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/89" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/89?utm_source=stack-comment).

**Review by clarksandholtz — COMMENTED** [review]
Oh this is a good idea! I should do this on Android.

I get that we never use italic fonts, but isn't it possible for the user to configure the font weight to where we would need some of these like Circular Black?

**Comment by lucillebenoit** [comment]
> Oh this is a good idea! I should do this on Android.
> 
> I get that we never use italic fonts, but isn't it possible for the user to configure the font weight to where we would need some of these like Circular Black?

Not on iOS because we can't modify the font weight separate from the font family! I was also checking out Affirm and Afterpay as examples and they only provide the exact fonts they use (2-3 only)

**Review by clarksandholtz — APPROVED** [review]

**Comment by lucillebenoit** [comment]
@lucillebenoit started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/89).

**Comment by lucillebenoit** [comment]
[Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/89) rebased this pull request as part of a merge.

**Comment by lucillebenoit** [comment]
@lucillebenoit merged this pull request with [Graphite](https://app.graphite.dev/github/pr/getcatch/catch-ios-sdk/89).

**Pull request merged**
